export const CALCULATOR_INIT = 'CALCULATOR_INIT';
export const CALCULATOR_SUCCESS = 'CALCULATOR_SUCCESS';
export const CALCULATOR_FAILURE = 'CALCULATOR_FAILURE';

export const TESTIMONIALS_INIT = 'TESTIMONIALS_INIT';
export const TESTIMONIALS_SUCCESS = 'TESTIMONIALS_SUCCESS';
export const TESTIMONIALS_FAILURE = 'TESTIMONIALS_FAILURE';

export const ROUTES_INIT = 'ROUTES_INIT';
export const ROUTES_SUCCESS = 'ROUTES_SUCCESS';
export const ROUTES_FAILURE = 'ROUTES_FAILURE';

export const CONFIGURATOR_INIT = 'CONFIGURATOR_INIT';
export const CONFIGURATOR_SUCCESS = 'CONFIGURATOR_SUCCESS';
export const CONFIGURATOR_FAILURE = 'CONFIGURATOR_FAILURE';
